/**
 * MAISON VITAL DATA STORE v2.1
 * Schéma préparé pour migration Supabase.
 * Les IDs sont des UUID simulés pour la cohérence future.
 */

export const INVENTORY = [
  {
    id: "asset_001",
    name: "Pommeau Douche",
    icon: "fa-shower",
    category: "plomberie",
    frequency_months: 3,
    duration_minutes: 10,
    xp_reward: 50,
    difficulty: "easy",
    climate_tags: ["global"],
    risk_description: "Risque de légionelles & Perte de débit (-30%)",
    products: ["Vinaigre Blanc", "Sac Congélation"],
    steps: [
      "Verser vinaigre blanc dans un sac.",
      "Attacher le sac au pommeau avec un élastique.",
      "Laisser agir 2h minimum.",
      "Frotter les picots et rincer.",
    ],
  },
  {
    id: "asset_002",
    name: "Lave-Linge (Filtre)",
    icon: "fa-soap",
    category: "electromenager",
    frequency_months: 2,
    duration_minutes: 5,
    xp_reward: 30,
    difficulty: "easy",
    climate_tags: ["global"],
    risk_description: "Panne pompe de vidange & Mauvaises odeurs",
    products: ["Bassine", "Chiffon"],
    steps: [
      "Ouvrir la trappe d'accès au filtre (généralement en bas).",
      "Placer une bassine et dévisser doucement pour vider l'eau.",
      "Retirer le filtre et nettoyer les résidus sous l'eau.",
      "Remonter le tout et vérifier l'étanchéité.",
    ],
  },
  {
    id: "asset_003",
    name: "VMC / Aération",
    icon: "fa-fan",
    category: "air",
    frequency_months: 6,
    duration_minutes: 15,
    xp_reward: 80,
    difficulty: "medium",
    climate_tags: ["humid", "temperate"],
    risk_description: "Moisissures, Allergies & Surconsommation chauffage",
    products: ["Eau savonneuse", "Escabeau"],
    steps: [
      "Démonter les bouches d'extraction (cuisine, SDB).",
      "Laver les grilles à l'eau savonneuse.",
      "Dépoussiérer l'intérieur du conduit accessible.",
      "Remonter les bouches une fois sèches.",
    ],
  },
  {
    id: "asset_004",
    name: "Détecteur Fumée",
    icon: "fa-bell",
    category: "securite",
    frequency_months: 12,
    duration_minutes: 2,
    xp_reward: 100,
    difficulty: "easy",
    climate_tags: ["global"],
    risk_description: "Défaillance en cas d'incendie (Sécurité Vitale)",
    products: ["Aspirateur", "Piles neuves (si besoin)"],
    steps: [
      "Dépoussiérer le détecteur avec l'aspirateur.",
      "Appuyer sur le bouton 'Test' jusqu'à la sonnerie.",
      "Vérifier la date de péremption au dos.",
      "Changer les piles si l'alarme semble faible.",
    ],
  },
  {
    id: "asset_005",
    name: "Chauffe-Eau (GS)",
    icon: "fa-temperature-arrow-up",
    category: "hvac",
    frequency_months: 12,
    duration_minutes: 45,
    xp_reward: 200,
    difficulty: "hard",
    climate_tags: ["global"],
    risk_description: "Fuite, Corrosion & Surconsommation (+20%)",
    products: ["Seau"],
    steps: [
      "Couper l'arrivée d'eau froide.",
      "Ouvrir un robinet d'eau chaude pour casser la pression.",
      "Actionner la purge du groupe de sécurité (bouton rouge/bleu).",
      "Laisser couler un peu d'eau, puis refermer.",
    ],
  },
  {
    id: "asset_006",
    name: "Gouttières",
    icon: "fa-cloud-rain",
    category: "exterieur",
    frequency_months: 6,
    duration_minutes: 60,
    xp_reward: 150,
    difficulty: "hard",
    climate_tags: ["temperate", "rainy"],
    risk_description: "Infiltration d'eau en façade & Murs humides",
    products: ["Échelle", "Gants", "Jet d'eau"],
    steps: [
      "Sécuriser l'échelle sur un sol stable.",
      "Retirer les feuilles et débris à la main (avec gants).",
      "Rincer la gouttière au jet d'eau.",
      "Vérifier que l'eau s'écoule bien dans la descente.",
    ],
  },
];
